### ISSUE TITLE
初始化失败，使用报空了

### ISSUE THREAD

**Issue by ail36413** [jinguangyang/ChineseTTS#4]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.air4.chinesetts.tts.InputWorker.interrupt()' on a null object reference
                                                                                                    	at com.air4.chinesetts.tts.TtsManager.stopTts(TtsManager.java:86)
                                                                                                    	at com.air4.chinesetts.tts.TtsManager.speak(TtsManager.java:91)
                                                                                                    	at com.bohai.myapplication.MainActivity$2.onClick(MainActivity.java:43)
                                                                                                    	at android.view.View.performClick(View.java:7659)
                                                                                                    	at android.view.View.performClickInternal(View.java:7636)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30156)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:990)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8214)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1187)

**Comment by LY688** [comment]
你好，请问这个问题有解决吗
